plugins {
    alias(libs.plugins.weaver.android.library)
    alias(libs.plugins.weaver.android.library.compose)
}

android {
    namespace 'dev.mkao.weaver.features.shared'
}

dependencies {
    implementation project(':core:domain')
    implementation project(':core:common')
    implementation project(':core:designsystem')

    implementation libs.androidx.lifecycle.runtime.compose
    implementation libs.material.icons.extended
    implementation libs.coil.compose
}
