plugins {
    alias(libs.plugins.weaver.android.application)
    alias(libs.plugins.weaver.android.application.compose)
    alias(libs.plugins.weaver.android.application.firebase)
    alias(libs.plugins.weaver.android.hilt)
    alias(libs.plugins.weaver.android.room)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.ksp)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.detekt)
    alias(libs.plugins.baseline.profiles)
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

def versionPropsFile = rootProject.file("version.properties")
def versionProps = new Properties()
if (versionPropsFile.exists()) {
    versionProps.load(new FileInputStream(versionPropsFile))
}

android {
    namespace 'dev.mkao.weaver'

    defaultConfig {
        applicationId "dev.mkao.weaver"
        versionCode versionProps.getProperty("VERSION_CODE", "1").toInteger()
        versionName versionProps.getProperty("VERSION_NAME", "1.0")
    }

    signingConfigs {
        release {
            def keystorePath = System.getenv("ANDROID_KEYSTORE_FILE")
            if (keystorePath != null) {
                storeFile = file(keystorePath)
                storePassword = System.getenv("KEYSTORE_PASSWORD")
                keyAlias = System.getenv("KEY_ALIAS")
                keyPassword = System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            if (signingConfigs.release.storeFile != null) {
                signingConfig signingConfigs.release
            } else {
                println "Release keystore not found, using debug signing config."
                signingConfig signingConfigs.debug
            }
            minifyEnabled true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildTypes.each {
        def gnewsApiKey = localProperties.getProperty("GNEWS_API_KEY") ?: "\"${System.getenv("GNEWS_API_KEY") ?: ""}\""
        it.buildConfigField('String', 'GNEWS_API_KEY', gnewsApiKey)
    }

    kotlinOptions {
        freeCompilerArgs = ['-XXLanguage:+PropertyParamAnnotationDefaultTargetMode']
    }

    hilt {
        enableAggregatingTask = true
    }
}

detekt {
    config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
    buildUponDefaultConfig = true
}

dependencies {
    implementation project(':resources')
    implementation project(':core:domain')
    implementation project(':core:common')
    implementation project(':core:designsystem')
    implementation project(':core:data')

    // Feature modules
    implementation project(':features:shared')
    implementation project(':features:home')
    implementation project(':features:categories')
    implementation project(':features:details')
    implementation project(':features:search')
    implementation project(':features:bookmarks')
    implementation project(':features:settings')
    implementation project(':features:onboarding')
    implementation project(':features:languages')
    implementation project(':features:videofeed')
    implementation project(':features:about')
    implementation project(':features:widget')

    detektPlugins libs.detekt.formatting

    implementation libs.androidx.core.ktx
    implementation libs.androidx.core.splashscreen
    implementation libs.androidx.appcompat
    implementation libs.android.material

    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.runtime.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.lifecycle.viewmodel.ktx

    implementation libs.material3.window.size.classes
    implementation libs.android.material3.adaptive
    implementation libs.android.material3.adaptive.layout
    implementation libs.android.material3.adaptive.navigation
    implementation libs.android.material3.adaptive.navigation.suite
    implementation libs.material.icons.extended
    implementation libs.androidx.activity.compose

    implementation libs.coil.compose
    implementation libs.compose.shimmer
    implementation libs.accompanist.permissions
    implementation libs.accompanist.systemuicontroller

    implementation libs.androidx.navigation3.runtime
    implementation libs.androidx.navigation3.ui
    implementation libs.androidx.lifecycle.viewmodel.navigation3
    implementation libs.kotlinx.serialization.json

    implementation libs.android.hilt.navigation.compose
    implementation libs.android.hilt.work
    ksp libs.android.hilt.work.compiler

    implementation libs.work.runtime.ktx

    implementation libs.retrofit
    implementation libs.converter.moshi
    implementation libs.converter.gson
    implementation libs.gson
    implementation libs.jsoup
    implementation libs.okhttp
    implementation libs.logging.interceptor
    implementation libs.moshi
    implementation libs.moshi.kotlin
    ksp libs.moshi.kotlin.codegen

    implementation libs.androidx.browser

    implementation libs.media3.exoplayer
    implementation libs.media3.ui
    implementation libs.android.youtube.player

    implementation libs.datastore.preferences

    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    implementation libs.timber
    debugImplementation libs.chucker.debug
    releaseImplementation libs.chucker.release
    debugImplementation libs.leakcanary.android

    implementation libs.profileinstaller
    baselineProfile project(':baselineprofile')

    testImplementation libs.junit
    testImplementation libs.kotlinx.coroutines.test
    testImplementation libs.turbine
    testImplementation libs.androidx.arch.core.testing
    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin
    testImplementation libs.androidx.work.testing
    testImplementation libs.compose.ui.test.junit4
    kspTest libs.hilt.android.compiler

    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.compose.ui.test.junit4
    androidTestImplementation libs.room.testing
    androidTestImplementation libs.androidx.work.testing
    androidTestImplementation libs.hilt.android.testing
    androidTestImplementation libs.mockito.android
    androidTestImplementation libs.mockito.kotlin
    kspAndroidTest libs.hilt.android.compiler
}
