# Add project specific ProGuard rules here.

# ---------------------------------------------------------------------------
# jsoup 1.22.x optionally delegates to Google's re2j regex engine when present.
# We do not ship re2j, so these references are dead code paths — safe to ignore
# (auto-generated by R8 in build/outputs/mapping/release/missing_rules.txt).
# ---------------------------------------------------------------------------
-dontwarn com.google.re2j.Matcher
-dontwarn com.google.re2j.Pattern

# ---------------------------------------------------------------------------
# Kotlin / Kotlinx Metadata (R8 parses Kotlin metadata for kotlinx-serialization,
# Moshi codegen, etc.). Keep metadata so reflection-free serializers still work.
# ---------------------------------------------------------------------------
-keepclassmembers class kotlin.Metadata {
    public <methods>;
}

# ---------------------------------------------------------------------------
# kotlinx.serialization — keep @Serializable classes + generated serializers.
# ---------------------------------------------------------------------------
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt
-keepclassmembers class * {
    @kotlinx.serialization.Serializable <methods>;
}
-keep,includedescriptorclasses class dev.mkao.weaver.**$$serializer { *; }
-keepclasseswithmembers class * {
    kotlinx.serialization.KSerializer serializer(...);
}

# ---------------------------------------------------------------------------
# Moshi — keep @JsonClass-annotated models and their field names.
# ---------------------------------------------------------------------------
-keep class **JsonAdapter {
    <init>(...);
    <fields>;
}
-keep @com.squareup.moshi.JsonClass interface * {
    *;
}
-keep @com.squareup.moshi.JsonClass class * {
    *;
}
-keepclassmembers class * {
    @com.squareup.moshi.FromJson <methods>;
    @com.squareup.moshi.ToJson <methods>;
}
# Network models are serialized by name — keep their fields intact.
-keep class dev.mkao.weaver.data.network.model.** { *; }

# ---------------------------------------------------------------------------
# Retrofit / OkHttp — keep the service interface and its annotations.
# ---------------------------------------------------------------------------
-keepattributes Signature, Exceptions, RuntimeVisibleAnnotations, AnnotationDefault
-keep,allowobfuscation,allowshrinking interface retrofit2.Call
-keep,allowobfuscation,allowshrinking class retrofit2.Response
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation
-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn retrofit2.**
-dontwarn org.conscrypt.**
-dontwarn org.openjsse.**

# ---------------------------------------------------------------------------
# Room — generated implementations must be kept.
# ---------------------------------------------------------------------------
-keep class * extends androidx.room.RoomDatabase { <init>(); }
-dontwarn androidx.room.paging.**

# ---------------------------------------------------------------------------
# WorkManager / Hilt workers.
# ---------------------------------------------------------------------------
-keep class * extends androidx.work.ListenableWorker { <init>(...); }
-keep class * extends androidx.work.WorkerFactory { *; }
-keep public class * extends androidx.work.CoroutineWorker { public <init>(...); }

# Uncomment to preserve line numbers for debugging stack traces.
#-keepattributes SourceFile,LineNumberTable
#-renamesourcefileattribute SourceFile