default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'internal')
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
